config/routes.rb
Rails.application.routes.draw do
  root to: 'check_postcode#index'
  get 'check_postcode', to: 'check_postcode#index'
  post 'check_postcode', to: 'check_postcode#check'
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/supported_lsoa.rb
class SupportedLsoa < ApplicationRecord
  has_many :supported_postcodes, inverse_of: :supported_lsoa, dependent: :destroy

  validates :starts_with, presence: true, uniqueness: true
end

app/models/supported_postcode.rb
class SupportedPostcode < ApplicationRecord
  POSTCODE_REGEX = /\A[a-z]{1,2}\d[a-z\d]?\s*\d[a-z]{2}\Z/i

  belongs_to :supported_lsoa

  validates :postcode, presence: true, format: { with: POSTCODE_REGEX,
                                                 message: I18n.t('postcodes.errors.invalid_postcode_format') }

  def postcode=(postcode)
    self[:postcode] = postcode&.strip&.squish
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/check_postcode_controller.rb
class CheckPostcodeController < ApplicationController
  rescue_from ActionController::ParameterMissing, with: :missing_parameter

  def index; end

  def check
    result = CheckPostcodeService.instance.call(postcode_param)

    if result[:supported]
      render partial: 'check_postcode/success'
    else
      @error = result[:message]
      render partial: 'check_postcode/error'
    end
  end

  private

  def postcode_param
    params.require(:postcode)
  end

  def missing_parameter
    @error = I18n.t('postcodes.errors.mandatory_postcode')
    render status: :unprocessable_entity, partial: 'check_postcode/error'
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/check_postcode/_error.html.erb
<p style="color:white;background-color:red"><%= @error %></p>
<br/>
<%= link_to t('postcodes.view.back_to_form_link'), check_postcode_path %>

app/views/check_postcode/_success.html.erb
<p style="color:white;background-color:green"><%= t('postcodes.messages.postcode_supported') %></p>
<br/>
<%= link_to t('postcodes.view.back_to_form_link'), check_postcode_path %>

app/views/check_postcode/index.html.erb
<%= form_tag check_postcode_path, method: :post do %>
  <%= label :postcode, t('postcodes.view.form.prompt') %>
  <%= text_field_tag :postcode, nil, required: true %>
  <%= hidden_field_tag :authenticity_token, form_authenticity_token %>
  <%= button_tag t('postcodes.view.form.button'), type: :submit %>
<% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>PostcodeChecker</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>